[package]
name = "edumdns"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
edumdns_core = { path = "edumdns_core" }
edumdns_probe = { path = "edumdns_probe" }
edumdns_server = { path = "edumdns_server" }
thiserror = "2.0.12"
tokio = {version =  "1.44.2", features = ["full"] }
log = "0.4.27"
env_logger = "0.11.8"
dotenvy = "0.15.7"

[workspace]
members = [
    "edumdns_core",
    "edumdns_probe",
    "edumdns_server"
, "edumdns_web"]
